#!/bin/bash -ae
#
# shutdown an application

abspath=$(cd -P ${0%/*} && echo $PWD/${0##*/}) # absolute path of this script
scripts_dir=`dirname "$abspath"` # scripts dir (i.e. where this script is located)
packages_dir=$(cd -P $scripts_dir/../.. && echo $PWD) # root of this package 

hostname=`hostname`
app_name="pyserver"

echo "Shutdown app $app_name"
echo "abspath = $abspath"
echo "scripts_dir = $scripts_dir"
echo "packages_dir = $packages_dir"

nodaemon=false
if [[ $1 == "nodaemon" ]]; then
    nodaemon=true
fi
echo "nodaemon = $nodaemon"

echo "Stopping in $PWD"
cd $packages_dir
if [[ $nodaemon == false ]] && [[ -f $packages_dir/$app_name.pid ]]; then
    echo "Stopping `cat $packages_dir/$app_name.pid`"
    kill `cat $packages_dir/$app_name.pid`
    rm -f $packages_dir/$app_name.pid
fi

echo "Done."
exit 0
