#!/bin/bash -ae
# this script activate an application

abspath=$(cd -P ${0%/*} && echo $PWD/${0##*/}) # absolute path of this script
scripts_dir=`dirname "$abspath"` # scripts dir (i.e. where this script is located)
packages_dir=$(cd -P $scripts_dir/../.. && echo $PWD) # package root

app_name="helloworld"

app_dir="$packages_dir/$app_name" # app code
rt_dir="$packages_dir/container_runtime" # container runtime

echo "Activate app $app_name"
echo "abspath = $abspath"
echo "scripts_dir = $scripts_dir"
echo "packages_dir = $packages_dir"
echo "app_dir = $app_dir"
echo "rt_dir = $rt_dir"

echo "Precompiling application"
$rt_dir/play precompile $app_dir; sleep 1;

exit 0
