#!/bin/bash -ae
#
# shutdown an application

abspath=$(cd -P ${0%/*} && echo $PWD/${0##*/}) # absolute path of this script
scripts_dir=`dirname "$abspath"` # scripts dir (i.e. where this script is located)
packages_dir=$(cd -P $scripts_dir/../.. && echo $PWD) # root of this package 

hostname=`hostname`
app_name="helloworld"

app_dir=$packages_dir/$app_name  # used to start the app
rt_dir="$packages_dir/container_runtime" # location of container runtime

echo "Shutdown app $app_name"
echo "abspath = $abspath"
echo "scripts_dir = $scripts_dir"
echo "packages_dir = $packages_dir"
echo "app_dir = $app_dir"
echo "rt_dir = $rt_dir"

nodaemon=false
if [[ $1 == "nodaemon" ]]; then
    nodaemon=true
fi

cd $packages_dir
echo "Stopping in $PWD"
if [[ $nodaemon == false ]]; then
    $rt_dir/play stop $app_dir
fi

echo "Done."
exit 0
