#!/bin/bash 
# this script activate an application

abspath=$(cd -P ${0%/*} && echo $PWD/${0##*/}) # absolute path of this script
scripts_dir=`dirname "$abspath"` # scripts dir (i.e. where this script is located)
packages_dir=$(cd -P $scripts_dir/../.. && echo $PWD) # package root

rt_dir="$packages_dir/container_runtime" # container runtime

echo "Activate app $app_name"
echo "abspath = $abspath"
echo "scripts_dir = $scripts_dir"
echo "packages_dir = $packages_dir"
echo "app_dir = $app_dir"
echo "rt_dir = $rt_dir"


echo -e "Creating container logs folder..."
mkdir -p $container_home/logs
chmod 755 $container_home/logs

echo -e "Setting the required permissions to container bin directory"
chmod 755 $container_home/bin/*

echo -e "Copying web application to container..."
war_dir=$packages_dir/wars
echo -e "war_dir = $war_dir"
cd $war_dir

for app in $war_dir/*.war
do
   echo "app is $app"
   #cp $app $container_home/webapps
   app_dir=${app##*/}
   app_dir=${app_dir%.war}
   mkdir -p $rt_dir/webapps/$app_dir
   echo -e "Unzip $app to $rt_dir/webapps/$app_dir"
   cd $rt_dir/webapps/$app_dir
   jar xvf $app
done

echo -e "Activated application"

exit 0
