#!/bin/bash -ae
# deactivate an application

abspath=$(cd -P ${0%/*} && echo $PWD/${0##*/}) # absolute path of this script
scripts_dir=`dirname "$abspath"` # scripts dir (i.e. where this script is located)
packages_dir=$(cd -P $scripts_dir/../.. && echo $PWD) # package root

rt_dir="$packages_dir/container_runtime" # container runtime

echo "abspath = $abspath"
echo "scripts_dir = $scripts_dir"
echo "packages_dir = $packages_dir"
echo "rt_dir = $rt_dir"

echo "Delete inflated web application from container..."
war_dir=$packages_dir/wars
echo "war_dir is $war_dir"

for app in $war_dir/*.war
do
   echo "app is $app"
   app_dir=${app##*/}
   app_dir=${app_dir%.war}
   echo "Delete $app from $war_dir/webapps/$app_dir"
   rm -rf $rt_dir/webapps/$app_dir
done

echo "Deactivated application"

exit 0
