#!/bin/bash

echo "Checking availability of java runtime"

JAVA_VER=$(java -version 2>&1 | sed 's/.* version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')
[ "$JAVA_VER" -ge 15 ] && echo "ok, java is 1.5 or newer"; exit 0 || echo "java is not availble or too old"; exit -1

