#!/bin/bash 
# install an application

abspath=$(cd -P ${0%/*} && echo $PWD/${0##*/}) # absolute path of this script
scripts_dir=`dirname "$abspath"` # scripts dir (i.e. where this script is located)
packages_dir=$(cd -P $scripts_dir/../.. && echo $PWD) # package root

rt_dir="$packages_dir/container_runtime" # container runtime

echo "Install app $app_name"
echo "abspath = $abspath"
echo "scripts_dir = $scripts_dir"
echo "packages_dir = $packages_dir"
echo "app_dir = $app_dir"
echo "rt_dir = $rt_dir"

echo "Checking availability of java runtime"

JAVA_VER=$(java -version 2>&1 | sed 's/.* version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')
[ "$JAVA_VER" -ge 15 ] && echo "ok, java is 1.5 or newer"; exit 0 || echo "java is not availble or too old"; exit -1

exit 0
