#!/bin/bash -ae

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
echo "scripts_dir $scripts_dir"

if [ ! -z "$UPSTARTSERVICE" ]; then
    echo "Stop service already by upstart"
else
    echo "Stop service without upstart"
    $scripts_dir/../../container_runtime/bin/catalina.sh stop
fi

echo "\nDone shutdown"
