#!/bin/bash -ae

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
echo "scripts_dir $scripts_dir"

validation_url="http://localhost:8080/helloworld"

if [ ! -z "$1" ]; then
    echo "Starting app nodaemon"
    $scripts_dir/../../container_runtime/bin/catalina.sh run
else
    echo 'Starting app'
    $scripts_dir/../../container_runtime/bin/catalina.sh start
fi

echo -e "Waiting for application to start completely..."

# poll until the application started completely
while true;
do
   export status=$(curl -s -L --head -o /dev/null -w "%{http_code}" $validation_url)
   # check if the status has a non-zero length
   if [ "$status" == 000 ]
   then
      echo "Application has yet started. status=$status"
      sleep 1
   else
      echo "Application has started!! status=$status"
      break
   fi
done

exit 0

